feat: created notification bell
NewSchoolApp/newschool-frontend-mobile pull request #8
Opened 2021-03-04 22:38 UTC by TioDaniloBR

2021-03-07 03:36 UTC, RanderGabriel requested changes
Apontei algumas mudanças sugeridas nos arquivos. No mais, ficou muito legal a implementação 😄

2021-03-07 03:36 UTC, RanderGabriel commented on README.md
> +Esse repositório contém a implementação de uma versão inicial da rearquitetura do projeto **[NewSchoolApp](https://github.com/NewSchoolApp/newschool-frontend)**. Se trata de uma tentativa de migração
Aqui é Nuxt mesmo. Next é outra ferramenta

2021-03-07 03:36 UTC, RanderGabriel commented on app/components/atoms/notification-bell/notification-bell.styles.ts
> +export const Style = StyleSheet.create({
Para estilização estamos usando styled-components

2021-03-07 23:30 UTC, msalvexx requested changes

2021-03-07 23:30 UTC, msalvexx commented on app/components/atoms/notification-bell/notification-bell.tsx
> +import BellHome from '../../../assets/home-bell';
Tenta padronizar esses paths com '../../' para facilitar a leitura da pasta em que a dependência está.

2021-03-09 03:55 UTC, HenrryEsposito commented
@TioDaniloBR  Seu componente funciona bem apensar alguns erros pontuais. Acredito que há apenas um erro aqui não podemos deixar passar que seria simples até de resolver, você considerou o Notification Bell como sendo um componente do tipo átomo, quando, na verdade, ele deve ser uma molécula, pois ele mesmo utiliza outros componentes prontos em sua estrutura, um deles sendo o Badge do React Native Paper.

2021-03-13 18:50 UTC, RanderGabriel commented on app/components/molecules/notification-bell/notification-bell.styles.ts
> +// export const Style = StyleSheet.create({
Seria legal remover esse comentário aqui

2021-03-13 19:06 UTC, TioDaniloBR commented on app/components/molecules/notification-bell/notification-bell.styles.ts
> +// export const Style = StyleSheet.create({
Sim. Esqueci de remover.

2021-03-16 13:21 UTC, merged